server:
  port: 10011

spring:
  jpa:
    database: MYSQL
    show-sql: true
#    properties:
#      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://172.16.0.15:3306/sign?characterEncoding=utf8
    username: root
    password: Zheng1234

logging:
  file: sign.log




